### ISSUE TITLE
Train classification models on MusicAudioSet / US8K

### ISSUE THREAD

**Issue by jtcramer** [marl/l3embedding#25]
#### original model -- @hohsiangwu 
- [x] L3 embedding / original model / music set / 6K pooling / framewise / overlap / svm
- [x] L3 embedding / original model / music set / 6K pooling / summary stats /  overlap / svm
- [x] L3 embedding / original model / music set / 512 pooling / framewise /  overlap / svm
- [x] L3 embedding / original model / music set / 512 pooling / summary stats /  overlap / svm
- [x] L3 embedding / original model / music set / 6K pooling / framewise /  overlap / mlp
- [x] L3 embedding / original model / music set / 6K pooling / summary stats /  overlap / mlp
- [x] L3 embedding / original model / music set / 512 pooling / framewise /  overlap / mlp
- [x] L3 embedding / original model / music set / 512 pooling / summary stats /  overlap / mlp
- [x] L3 embedding / original model / music set / 6K pooling / framewise / no-overlap / svm
- [x] L3 embedding / original model / music set / 6K pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / original model / music set / 512 pooling / framewise /  no-overlap / svm
- [x] L3 embedding / original model / music set / 512 pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / original model / music set / 6K pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / original model / music set / 6K pooling / summary stats /  no-overlap / mlp
- [x] L3 embedding / original model / music set / 512 pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / original model / music set / 512 pooling / summary stats /  no-overlap / mlp

##### @hohsiangwu 
- [x] L3 embedding / alternative normalization / music set / 6K pooling / framewise /  overlap / svm
- [x] L3 embedding / alternative normalization / music set / 6K pooling / summary stats /  overlap / svm
- [x] L3 embedding / alternative normalization / music set / 512 pooling / framewise /  overlap / svm
- [x] L3 embedding / alternative normalization / music set / 512 pooling / summary stats /  overlap / svm
- [x] L3 embedding / alternative normalization / music set / 6K pooling / framewise /  overlap / mlp
##### @jtcramer
- [x] L3 embedding / alternative normalization / music set / 6K pooling / summary stats /  overlap / mlp
- [x] L3 embedding / alternative normalization / music set / 512 pooling / framewise /  overlap / mlp

##### @justinsalamon (001-009)
- [x] L3 embedding / alternative normalization / music set / 512 pooling / summary stats /  overlap / mlp
- [x] L3 embedding / alternative normalization / music set / 512 pooling / summary stats /  no-overlap / mlp
- [x] L3 embedding / alternative normalization / music set / 512 pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / alternative normalization / music set / 512 pooling / framewise /  no-overlap / svm
- [x] L3 embedding / alternative normalization / music set / 512 pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / alternative normalization / music set / 6K pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / alternative normalization / music set / 6K pooling / summary stats /  no-overlap / mlp
- [x] L3 embedding / alternative normalization / music set / 6K pooling / framewise /  no-overlap / svm
- [x] L3 embedding / alternative normalization / music set / 6K pooling / framewise /  no-overlap / mlp

#### melspec1 -- @justinsalamon (010-025)
- [x] L3 embedding / melspec1 / music set / 6K pooling / framewise / overlap / svm
- [x] L3 embedding / melspec1 / music set / 6K pooling / framewise / overlap / mlp
- [x] L3 embedding / melspec1 / music set / 6K pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / melspec1 / music set / 6K pooling / framewise / no-overlap / svm
- [x] L3 embedding / melspec1 / music set / 6K pooling / summary stats / no-overlap / svm
- [x] L3 embedding / melspec1 / music set / 6K pooling / summary stats /  no-overlap / mlp
- [x] L3 embedding / melspec1 / music set / 6K pooling / summary stats / overlap / svm
- [x] L3 embedding / melspec1 / music set / 6K pooling / summary stats / overlap / mlp
- [x] L3 embedding / melspec1 / music set / 512 pooling / framewise / overlap / mlp
- [x] L3 embedding / melspec1 / music set / 512 pooling / framewise / overlap / svm
- [x] L3 embedding / melspec1 / music set / 512 pooling / framewise / no-overlap / svm
- [x] L3 embedding / melspec1 / music set / 512 pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / melspec1 / music set / 512 pooling / summary stats /  no-overlap / mlp
- [x] L3 embedding / melspec1 / music set / 512 pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / melspec1 / music set / 512 pooling / summary stats / overlap / svm
- [x] L3 embedding / melspec1 / music set / 512 pooling / summary stats / overlap / mlp

#### melspec2 -- @jtcramer
- [ ] L3 embedding / melspec2 / music set / 6K pooling / framewise /  overlap / svm
- [x] L3 embedding / melspec2 / music set / 6K pooling / summary stats /  overlap / svm
- [x] L3 embedding / melspec2 / music set / 512 pooling / framewise /  overlap / svm
- [x] L3 embedding / melspec2 / music set / 512 pooling / summary stats /  overlap / svm
- [x] L3 embedding / melspec2 / music set / 6K pooling / framewise /  overlap / mlp
- [x] L3 embedding / melspec2 / music set / 6K pooling / summary stats /  overlap / mlp
- [x] L3 embedding / melspec2 / music set / 512 pooling / framewise /  overlap / mlp
- [x] L3 embedding / melspec2 / music set / 512 pooling / summary stats /  overlap / mlp
- [x] L3 embedding / melspec2 / music set / 6K pooling / framewise / no-overlap / svm
- [x] L3 embedding / melspec2 / music set / 6K pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / melspec2 / music set / 512 pooling / framewise /  no-overlap / svm
- [x] L3 embedding / melspec2 / music set / 512 pooling / summary stats /  no-overlap / svm
- [x] L3 embedding / melspec2 / music set / 6K pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / melspec2 / music set / 6K pooling / summary stats /  no-overlap / mlp
- [x] L3 embedding / melspec2 / music set / 512 pooling / framewise /  no-overlap / mlp
- [x] L3 embedding / melspec2 / music set / 512 pooling / summary stats /  no-overlap / mlp

### SoundNet -- @hohsiangwu 
- [x] SoundNet / framewise / svm
- [x] SoundNet / summary stats / svm
- [x] SoundNet / framewise / mlp
- [x] SoundNet / summary stats / mlp

### VGGish -- @jtcramer
- [x] VGGish / framewise /  overlap / svm
- [x] VGGish / summary stats /  overlap / svm
- [x] VGGish / framewise /  overlap / mlp
- [x] VGGish / summary stats /  overlap / mlp
- [x] VGGish / framewise /  no-overlap / svm
- [x] VGGish / summary stats /  no-overlap / svm
- [x] VGGish / framewise /  no-overlap / mlp
- [x] VGGish / summary stats /  no-overlap / mlp

**Comment by jtcramer** [comment]
Feature paths -> #24

**Comment by justinsalamon** [comment]
## Instructions
To train the classifier, make edit or make a copy of `jobs/classifier-train-array.sbatch` In there, you'll want to make the following changes:

1. Change the email to your email
2. Change the anaconda environment name
3. Change `SRCDIR` to whatever directory the `l3embedding` repository is in
4. Change `FEATURES_DIR` to the directory where the features are
5. Change `OUTPUT_DIR` to your general experiment output directory. A subdirectory called `classifier` will be created here for the classifier output.
6. Change `MODEL_DIR` to the type of model you want to train. Options are `svm` or `mlp`.
7. Change `FEATURE_MODE` to the type of feature preprocessing you want to perform. Options are `framewise` or `stats`.
8. Change `GOOGLE_DEV_APP_NAME` and `GSHEET_ID` if you want to sync the results with a Google Docs spreadsheet.
9. Add `--non-overlap` as an argument if you want to do a run with no overlapping frames.
10. Add any additional command line arguments to the script call. Take a look at `06_train_classifier.py` for the options.
11. Run `sbatch --array=1-10 classifier-train-array.sbatch`
