### ISSUE TITLE
Generate features for EnvAudioSet / US8K

### ISSUE THREAD

**Issue by jtcramer** [marl/l3embedding#32]
#### original model
- [x] L3 embedding / original model / music set / 6K pooling -- @jtcramer
`/scratch/jtc440/sonyc-usc/features/us8k/l3/original/environmental/cnn_L3_orig/`
- [x] L3 embedding / original model / music set / 512 pooling -- @jtcramer
`/scratch/jtc440/sonyc-usc/features/us8k/l3/short/environmental/cnn_L3_orig/`

#### alternative normalization
- [x] L3 embedding / alternative normalization / music set / 6K pooling  -- @hohsiangwu 
`/scratch/hhw230/sonyc-usc/features/us8k/l3/original/environmental/cnn_L3_kapredbinputbn`
- [x] L3 embedding / alternative normalization / music set / 512 pooling  -- @hohsiangwu 
`/scratch/hhw230/sonyc-usc/features/us8k/l3/short/environmental/cnn_L3_kapredbinputbn`
#### melspec1
- [x] L3 embedding / melspec1 / music set / 6K pooling -- @jtcramer
`/scratch/jtc440/sonyc-usc/features/us8k/l3/original/environmental/cnn_L3_melspec1`
- [x] L3 embedding / melspec1 / music set / 512 pooling  -- @hohsiangwu 
`/scratch/hhw230/sonyc-usc/features/us8k/l3/short/environmental/cnn_L3_melspec1`

#### melspec2
- [x] L3 embedding / melspec2 / music set / 6K pooling -- @jtcramer 
`/scratch/jtc440/sonyc-usc/features/us8k/l3/original/environmental/cnn_L3_melspec2`
- [x] L3 embedding / melspec2 / music set / 512 pooling -- @hohsiangwu
`/scratch/hhw230/sonyc-usc/features/us8k/l3/short/environmental/cnn_L3_melspec2`

**Comment by hohsiangwu** [comment]
- cnn_L3_orig:
`/scratch/hhw230/sonyc-usc/embedding/environmental/cnn_L3_orig/20180321213449/model_best_valid_accuracy.h5`

- cnn_L3_kapredbinputbn:
`/scratch/hhw230/sonyc-usc/embedding/environmental/cnn_L3_kapredbinputbn/20180315104305/model_best_valid_accuracy.h5`

- cnn_L3_melspec1:
`/scratch/hhw230/sonyc-usc/embedding/environmental/cnn_L3_melspec1/20180315145929/model_best_valid_accuracy.h5`

**Comment by justinsalamon** [comment]
I'm copying over the instructions with #33, please double check they're correct:

## Instructions
To generate samples (for L3 embedding models), make edit or make a copy of `jobs/generate_embedding_samples_array_us8k.sbatch` In there, you'll want to make the following changes:

0. **Make sure that the embedding model path follows the convention** `<output_dir>/embedding/environmental/<l3_model_type>/<timestamp>/model_best_valid_accuracy.h5`. **The code assumes this convention to be followed.**
1. Change the email to your email
2. Change the anaconda environment name
3. Change `SRCDIR` to whatever directory the `l3embedding` repository is in
4. Change `L3_MODEL_PATH` to the path of the `.h5` file of the model you want to use.
5. Change `L3_POOLING_TYPE` to the type of pooling (`original` or `short`).
6. Change `OUTPUT_DIR` to your general experiment output directory. A subdirectory called `features` will be created here for the embedding output.
7. Add any additional command line arguments to the script call. Take a look at `05_generate_embedding_samples.py` for the options. (shouldn't need to do for this though)
8. Run `sbatch --array=1-2 generate_embedding_samples_array_us8k.sbatch`
