### ISSUE TITLE
Generate features for EnvAudioSet / DCASE

### ISSUE THREAD

**Issue by jtcramer** [marl/l3embedding#34]
#### original model
- [x] L3 embedding / original model / music set / 6K pooling -- @jtcramer
`/scratch/jtc440/sonyc-usc/features/dcase2013/l3/original/environmental/cnn_L3_orig`
- [x] L3 embedding / original model / music set / 512 pooling -- @jtcramer
`/scratch/jtc440/sonyc-usc/features/dcase2013/l3/short/environmental/cnn_L3_orig`

#### alternative normalization
- [x] L3 embedding / alternative normalization / music set / 6K pooling  -- @hohsiangwu 
`/scratch/hhw230/sonyc-usc/features/dcase2013/l3/original/environmental/cnn_L3_kapredbinputbn`
- [x] L3 embedding / alternative normalization / music set / 512 pooling  -- @hohsiangwu 
`/scratch/hhw230/sonyc-usc/features/dcase2013/l3/short/environmental/cnn_L3_kapredbinputbn`

#### melspec1
- [x] L3 embedding / melspec1 / music set / 6K pooling -- @jtcramer
`/scratch/jtc440/sonyc-usc/features/dcase2013/l3/original/environmental/cnn_L3_melspec1`
- [x] L3 embedding / melspec1 / music set / 512 pooling  -- @hohsiangwu 
`/scratch/hhw230/sonyc-usc/features/dcase2013/l3/short/environmental/cnn_L3_melspec1`

#### melspec2
- [x] L3 embedding / melspec2 / music set / 6K pooling -- @jtcramer 
`/scratch/jtc440/sonyc-usc/features/dcase2013/l3/original/environmental/cnn_L3_melspec2`
- [x] L3 embedding / melspec2 / music set / 512 pooling -- @hohsiangwu
`/scratch/hhw230/sonyc-usc/features/dcase2013/l3/short/environmental/cnn_L3_melspec2`

**Comment by hohsiangwu** [comment]
- cnn_L3_orig:
`/scratch/hhw230/sonyc-usc/embedding/environmental/cnn_L3_orig/20180321213449/model_best_valid_accuracy.h5`

- cnn_L3_kapredbinputbn:
`/scratch/hhw230/sonyc-usc/embedding/environmental/cnn_L3_kapredbinputbn/20180315104305/model_best_valid_accuracy.h5`

- cnn_L3_melspec1:
`/scratch/hhw230/sonyc-usc/embedding/environmental/cnn_L3_melspec1/20180315145929/model_best_valid_accuracy.h5`
