### ISSUE TITLE
Run multiple (4 more) experiments for esc50

### ISSUE THREAD

**Issue by hohsiangwu** [marl/l3embedding#44]
I have recycled previous issues and copied relevant information to create this new issue.

Make sure once you modify the script, queue the same script 4 times. I will take care of all environmental variations. And divide the music for both of you. Also @jtcramer could you also take care of VGGish, I don't have the instructions at hand but I think you still have it, right?

/cc @jtcramer @justinsalamon 

* ESC-50
    * Environmental @hohsiangwu
        * original
            * [x] 6K
            * [x] 512
        * altenative normalization
            * [x] 6K
            * [x] 512
        * melspec1
            * [x] 6K
            * [x] 512
        * melspec2
            * [x] 6K
            * [x] 512
    * Music
        * original @jtcramer 
            * [ ] 6K
            * [ ] 512
        * altenative normalization @jtcramer 
            * [ ] 6K
            * [ ] 512
        * melspec1 @justinsalamon 
            * [ ] 6K
            * [ ] 512
        * melspec2 @justinsalamon 
            * [ ] 6K
            * [ ] 512

Feature paths:
* #35 MusicAudioSet / ESC-50
* #36 EnvAudioSet / ESC-50

## Instructions
To train the classifier, make edit or make a copy of `jobs/classifier-train-array.sbatch` In there, you'll want to make the following changes:

1. Change the email to your email
2. Change the anaconda environment name
3. Change `SRCDIR` to whatever directory the `l3embedding` repository is in
4. Change `FEATURES_DIR` to the directory where the features are
5. Change `OUTPUT_DIR` to your general experiment output directory. A subdirectory called `classifier` will be created here for the classifier output.
6. ~Change `MODEL_DIR` to the type of model you want to train.~ This should remain `mlp`
7. ~Change `FEATURE_MODE` to the type of feature preprocessing you want to perform. Options are `framewise` or `stats`.~ This should remain `framewise`
8. Change `GOOGLE_DEV_APP_NAME` and `GSHEET_ID` if you want to sync the results with a Google Docs spreadsheet.
9. ~Add `--non-overlap` as an argument if you want to do a run with no overlapping frames.~ *But this shouldn't be necessary for this set of experiments.*
10. ~Add `--parameter-search-no-valid-fold` to use 4 folds for training, and then perform a 85-15 split to get a validation set. This is present in the template.~ This should remain set.
11. ~Add `--parameter-search-valid-ratio <float>` to change the validation ratio, when `--parameter-search-no-valid-fold` is used. This is present in the template.~ This should remain set
12. ~Add any additional command line arguments to the script call. Take a look at `06_train_classifier.py` for the options.~ *This will not be necessary for this set of experiments though.* This is only mentioned for posterity.
13. For ESC50: Run `sbatch --array=1-5 classifier-train-array.sbatch`

**Comment by hohsiangwu** [comment]
Yes, but this issue is for ESC50. I thought we are going to run US8K afterwards. I will modify the instructions.

**Comment by justinsalamon** [comment]
Shall we create a separate issue for US8K? I think we decided to run it one more time per-embedding, right?
